name: Build Java Swing App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Create output directory
        run: mkdir out

      - name: Compile Java sources
        shell: cmd
        run: |
          for /r src %%f in (*.java) do javac -d out "%%f"

      - name: Verify icons exist
        run: |
          if (-not (Test-Path "icons/icon.ico")) { throw "Missing icon.ico" }

      - name: Package Windows EXE
        run: |
          jpackage --verbose `
            --type exe `
            --input out `
            --main-class AutoKeyPresser `
            --main-jar AutoKeyPresser.jar `
            --name AutoKeyPresser `
            --icon icons/icon.ico

      - name: Upload Windows artifact
        uses: actions/upload-artifact@v4
        with:
          name: AutoKeyPresser-Windows
          path: AutoKeyPresser-*.exe

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Linux jpackage dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libfuse2 \
            fakeroot \
            binutils \
            xdg-utils \
            libasound2 \
            libgtk-3-0 \
            libnss3 \
            libx11-xcb1 \
            libxss1 \
            libxtst6 \
            libappindicator3-1 \
            libxrandr2 \
            libglib2.0-0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Create output directory
        run: mkdir out

      - name: Compile Java sources
        run: |
          find src -name "*.java" > sources.txt
          javac -d out @sources.txt

      - name: Verify icons exist
        run: |
          test -f icons/icon.png || (echo "Missing icon.png" && exit 1)

      - name: Package Linux AppImage
        run: |
          jpackage --verbose \
            --type app-image \
            --input out \
            --main-class AutoKeyPresser \
            --main-jar AutoKeyPresser.jar \
            --name AutoKeyPresser \
            --icon icons/icon.png

      - name: Upload Linux artifact
        uses: actions/upload-artifact@v4
        with:
          name: AutoKeyPresser-Linux
          path: AutoKeyPresser
