name: Build AutoKeyPresser

on:
  push:
    branches:
      - main
      - prod
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"

      - name: Install jpackage dependencies (Linux only)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libopenjfx-java libopenjfx-jni openjfx \
            fakeroot libasound2-dev libcups2-dev \
            libfontconfig1-dev libfreetype6-dev \
            libpng-dev libjpeg-dev libgif-dev \
            libxtst-dev libxt-dev libx11-dev libxext-dev \
            libxrandr-dev libxrender-dev libxinerama-dev

      - name: Compile Java sources
        run: |
          mkdir -p out/classes
          javac -d out/classes src/AutoKeyPresser.java

      - name: Create manifest file
        run: |
          echo "Main-Class: AutoKeyPresser" > manifest.txt

      - name: Create JAR file
        run: |
          jar cfm out/AutoKeyPresser.jar manifest.txt -C out/classes .

      - name: Verify JAR contents
        run: jar tf out/AutoKeyPresser.jar

      - name: Prepare icons
        run: |
          mkdir -p icons
          if [ ! -f icons/icon.ico ]; then
            echo "Windows icon missing! Creating placeholder..."
            curl -L -o icons/icon.ico https://raw.githubusercontent.com/james-paul25/AutoKeyPresser/main/icon.ico || true
          fi
          if [ ! -f icons/icon.png ]; then
            echo "Linux icon missing! Creating placeholder..."
            curl -L -o icons/icon.png https://raw.githubusercontent.com/james-paul25/AutoKeyPresser/main/icon.png || true
          fi

      - name: Package application
        run: |
          mkdir -p dist
          jpackage \
            --verbose \
            --input out \
            --main-jar AutoKeyPresser.jar \
            --main-class AutoKeyPresser \
            --name AutoKeyPresser \
            --app-version 1.0.0 \
            --type $([[ "${{ runner.os }}" == "Windows" ]] && echo "exe" || echo "app-image") \
            --icon $([[ "${{ runner.os }}" == "Windows" ]] && echo "icons/icon.ico" || echo "icons/icon.png") \
            --dest dist

      - name: Upload packaged app
        uses: actions/upload-artifact@v4
        with:
          name: AutoKeyPresser-${{ runner.os }}
          path: dist
